export const top5 = [
    {
      "id": 100111,
      "name": "LeBron James",
      "team": "Los Angeles Lakers",
      "description": "Selected first by the Cleveland Cavaliers His accomplishments include four NBA championships, four NBA Most Valuable Player (MVP) Awards, four Finals MVP Awards, and two Olympic gold medals. During his 17-year career, James holds the record for all-time playoffs points, is third in all-time points, and eighth in career assists. Career stats include: 27.1 Pts, 7.4 Ast, 7.4 Rbs",
      "position": "Small Forward",
      "number": 23,
      "nickname": "King James",
      "rating": 99,
      "birthdate": new Date("1984-12-30"),
      "drafted": 2003,
      "allstarVotes": 3770807,
      "poster": "https://m.media-amazon.com/images/I/519J0uvmn8L.jpg",
      "reviews": [],
      "added_at": new Date("2020-01-01"),
      "updated_at": new Date()
    },
    {
        "id": 100112,
        "name": "Kevin Durant",
        "team": "Brooklyn Nets",
        "description": "Selected second by the Oklahoma City Thunder. As a professional, he has won two NBA championships (both with the Golden State Warriors), an NBA Most Valuable Player Award, two Finals MVP Awards, two NBA All-Star Game Most Valuable Player Awards, four NBA scoring titles, the NBA Rookie of the Year Award, and two Olympic gold medals. Career stats include: 27.0 Pts, 4.1 Reb, 7.1 Reb",
        "position": "Small Forward",
        "number": 7,
        "nickname": "KD",
        "rating": 94,
        "birthdate": new Date("1988-09-29"),
        "drafted": 2007,
        "allstarVotes": 2432134,
        "poster": "https://i.etsystatic.com/21807813/r/il/b95073/2168575635/il_794xN.2168575635_e3li.jpg",
        "reviews": [],
        "added_at": new Date("2020-01-03"),
        "updated_at": new Date()
      },
      {
        "id": 100113,
        "name": "Anthony Davis",
        "team": "Los Angeles Lakers",
        "description": "Selected first by the New Orleans Pelicans. His accomplishments are, he has won one NBA championship, an seven-time NBA All-Star and has been named to four All-NBA First Teams and four NBA All-Defensive Teams. He also earned a gold medal with the 2012 US Olympic team. Career stats include: 24.0 Pts, 10.4 Reb, 2.4 Blk",
        "position": "Power Forward",
        "number": 3,
        "nickname": "The Brow",
        "rating": 96,
        "birthdate": new Date("1993-03-11"),
        "drafted": 2011,
        "allstarVotes": 955246,
        "poster": "https://m.media-amazon.com/images/I/51QFrxFFRkL.jpg",
        "reviews": [],
        "added_at": new Date("2020-01-05"),
        "updated_at": new Date()
      },
      {
        "id": 100114,
        "name": "Stephen Curry",
        "team": "Golden State Warriors",
        "description": "Selected seventh by the Golden State Warriors. A six-time NBA All-Star, Curry has been named the NBA Most Valuable Player (MVP) twice and won three NBA championships with the Warriors. Career stats include: 23.5 Pts, 4.5 Reb, 6.6 Ast",
        "position": "Point Guard",
        "number": 30,
        "nickname": "Chef Curry",
        "rating": 94,
        "birthdate": new Date("1988-03-14"),
        "drafted": 2009,
        "allstarVotes": 1191100,
        "poster": "https://i.etsystatic.com/21807813/r/il/254c44/2277475345/il_794xN.2277475345_nt4q.jpg",
        "reviews": [],
        "added_at": new Date("2020-01-07"),
        "updated_at": new Date()
      },
      {
        "id": 100115,
        "name": "James Harden",
        "team": "Houston Rockets",
        "description": "Selected third by the Oklahoma City Thunder. In 2018, Harden led the league in scoring and was named the NBA Most Valuable Player (MVP). He is an eight-time NBA All-Star and has earned All-NBA Team honors seven times, including six first-team selections. Career stats include: 25.2 Pts, 5.3 Reb, 6.3 Ast",
        "position": "Shooting Guard",
        "number": 13,
        "nickname": "The Beard",
        "rating": 95,
        "birthdate": new Date("1989-08-26"),
        "drafted": 2009,
        "allstarVotes": 102851,
        "poster": "https://i.etsystatic.com/21807813/r/il/f009dd/2216334986/il_794xN.2216334986_e8rl.jpg",
        "reviews": [],
        "added_at": new Date("2020-01-09"),
        "updated_at": new Date()
      }
  ]
  